### ISSUE TITLE
The translations for "friendssince" and "friendstatus" are not displaying correctly.

### ISSUE THREAD

**Issue by darkitxu84** [Bittoco/BitView-translations#53]
### Steps to Reproduce
1.  Go to the "My Account / Address Book" section
2.  Go to the "All Contacts" or "Incoming Invites" section
3.  Select a random friend

### Expected Behavior
The texts "Friends since" and "Friend Status" are displayed correctly depending on the language.

### Actual Behavior
The texts "Friends since" and "Friend Status" are only displayed in English.

### Screenshots
In the Español (México) language:

![image](https://github.com/Bittoco/BitView-translations/assets/76633266/6c00504a-ba7b-4302-9500-b833b19eca8b)

In Polski language:

![image](https://github.com/Bittoco/BitView-translations/assets/76633266/b27256aa-a3eb-4ab7-8078-dc3949cf4a97)

**Comment by vistafan12** [comment]
pinging @Herotrap

**Comment by darkitxu84** [comment]
oops, my bad. @vistafan12
Pull Request #55 is not really related to this issue.

This issue cannot be solved with a pull request to this repository.

**Comment by vistafan12** [comment]
Yeah, that's why I re-openned it. Waiting for Herotrap to see this
